# Generated by Django 5.1.3 on 2024-11-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_tips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safetytip',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='safetytip',
            name='date_posted',
        ),
        migrations.AlterField(
            model_name='safetytip',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
